---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dotnet-60
spec:
  tags:
  - from:
      kind: DockerImage
      name: registry.redhat.io/ubi8/dotnet-60:6.0-55
    name: 6.0-55
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mydotnet-60
spec:
  lookupPolicy:
    local: true
